### PR TITLE
fix missing type

### PR DESCRIPTION
**Pull request by koonpeng**
### Fixed bug

Fix missing type in task request.

### Fix applied

**If your pull request is a bug fix, delete this line and all the below lines.**

**If your pull request is a feature implementation, delete this line and all the above lines.**

### CODE REVIEW

**Comment by mxgrey** [comment]
The type should not be string. The type is intentionally left ambiguous because different categories of tasks are free to define whatever type for their description. Most of the type the description will be an object, but it could also be an array or anything else. The only requirement we want this schema to enforce is that some kind of description is provided.

**Comment by koonpeng** [comment]
Can we give it type `object`? The reason for this is because powerapps does not support ambiguous types, the closest to it would be `object`.

**Comment by mxgrey** [comment]
Hmmmm... The thing is I want to be able to support the possibility that someone would use an array, a string, a number, or whatever else as their task description if it suits their use case.

I apologize that I'm not familiar with powerapps. In what way does it fail if the schema has a field with an ambiguous type? It refuses to send/receive the message? It refuses to allow an `Any` type?

**Comment by koonpeng** [comment]
It simply refuses to import the api. i.e. it doesn't allow to use it at all, I haven't tried what happens if you put a wrong type, probably all requests will fail.

**Comment by mxgrey** [comment]
Out of curiosity, what would its behavior be if we don't mention `description` in the schema? Would it reject messages that include `description` in them? Or would it accept the messages but `description` information would be unavailable?

**Comment by mxgrey** [comment]
Another thought: What if we use `anyOf` with all possible types? For example:

```
"description" : {
  "anyOf": [
    { "type": "object" },
    { "type": "string" },
    { "type": "array" },
    { "type": "integer" },
    ... any others? ...
  ]
}
```

**Comment by koonpeng** [comment]
> Out of curiosity, what would its behavior be if we don't mention description in the schema? Would it reject messages that include description in them? Or would it accept the messages but description information would be unavailable?

My guess is that it would ignore it.

> Another thought: What if we use anyOf with all possible types? For example:

I think that looks good, it should be supported by powerapps.

**Comment by mxgrey** [comment]
Okay, if we can do `anyOf` with every JSON type listed, I'd be good with that. It would also do a better job of communicating to users that a description can truly be anything that their task category wants.

**Pull request closed without merging**
