### PR TITLE
Create dispatch task request/response messages

### PR DESCRIPTION
**Pull request by mxgrey**
These new message types will be used to indicate that a task request should be assigned to the best available fleet by the task dispatcher.

### CODE REVIEW

**Review by koonpeng — COMMENTED** [review]
Would it be possible for it to return a `TaskState` on success, so that it is easier for downstream to build a consistent flow?

When a user submits a task, we want the next refresh to show the new task. A task_id alone is not enough to show it on the list of tasks, without a task state, downstream must either create its own task state (which requires it to know how to create a task state from a task request, including task requests involving 3rd party phases/events), or wait for the first task state update (which may take up to a few secs).

**Comment by mxgrey** [comment]
Do you want the task state to be embedded in the response? Wouldn't it be simpler if the dispatch node simply publishes a task state over the usual websocket connection?

**Comment by koonpeng** [comment]
Having it in the response is easier because we don't want to return anything to the client until we write the task state into the db. Waiting on the ws will require us to keep state across different servers.

**Comment by mxgrey** [comment]
> Having it in the response is easier because we don't want to return anything to the client until we write the task state into the db. Waiting on the ws will require us to keep state across different servers.

I'm not sure I follow the logic here.

The way I think about it is this:

* The client makes a REST API request asking for a task to be dispatched.
* The api-server forwards that request to the ROS2 topic.
* The dispatcher node responds to the request saying "I acknowledge your request and am handling it. Now keep an eye out for a task with an ID of #xyz, that will be the task that you requested."
* At almost the exact same time, the dispatcher node will publish an initial task state over the websocket connection. The initial state will effectively say "This task is queued and waiting assignment".

I don't see a reason to have multiple channels of truth for the task state. I would think that just burdens the dashboard implementation with needing to handle multiple different sources of task state information. Especially when the task state will probably arrive over the websocket connection within milliseconds of the REST response (maybe even _before_ the REST response, depending on race conditions).

> we don't want to return anything to the client until we write the task state into the db

I think right now our use of databases is not very well defined, and that should be the next thing we focus on after we have this task pipeline functional. If we could have the task dispatch node ensure that the new task state is written into the database before it sends the response to the api-server, would that address your concerns? I know none of the ROS2 nodes currently write anything directly to the database, but I think we should start having them do that.

**Comment by mxgrey** [comment]
@koonpeng Per our discussion, I've updated the response message to include a task state field when the response is a successful one. I've also added a `dispatch` field to the task state where the dispatcher can put dispatch-related information.

**Comment by mxgrey** [comment]
I'm going to go ahead and merge this so we're not blocked on this PR. @koonpeng let me know if you have any remaining concerns and we can follow up in another PR.

**Pull request merged**
