### PR TITLE
Add schema for direct task assignment

### PR DESCRIPTION
**Pull request by Yadunund**
A schema for submitting task requests that should be directly assigned to a robot in a fleet.

### CODE REVIEW

**Review by mxgrey — APPROVED** [review]
Looks great!

**Review by mxgrey — CHANGES_REQUESTED** [review]
Oh but also we need a complementary `robot_task_response.json` schema.

**Comment by mxgrey** [comment]
For the response we can probably just copy the `dispatch_task_response.json`. I can't think of anything special about the direct robot request that would need a different type of response.

Nevertheless we should make a separate `.json` file for it so that the schemas can diverge in the future if they ever need to.

**Comment by Yadunund** [comment]
@mxgrey done! I was previously just reusing the `dispatch_task_response.json` schema but I've created a separate one now. Not sure if i'm using `$ref` correctly, so please let me know.

**Review by mxgrey — APPROVED** [review]
We could consider having a `base_task_response.json` that both `robot_..` and `dispatch_..` reference, but for the sake of quick iteration we can go with this approach :+1: 

The only danger here is that if we ever change `dispatch_task_response.json` we need to remember that `robot_task_response.json` is referencing it and will get changed as well if we don't do anything.

**Comment by Yadunund** [comment]
Gotcha. Will be mindful of that.

**Pull request merged**
